"""Embedding provider abstraction (vector-semantic-search PR#1 T1.3).

REQ-19: EmbeddingProvider ABC + lazy import contract.

Design D4 + D5 (design.md):
- The ABC is the contract surface for pluggable embedding models.
- The module-level import path MUST NOT pull torch or sentence_transformers.
  The real ``SentenceTransformersProvider`` (PR#2 T2.1) does a function-body
  import inside ``__init__``; this module stays import-clean.
- ``MockEmbeddingProvider`` returns hash-based deterministic unit-norm vectors
  of shape ``(len(texts), EMBEDDING_DIMS)``. Hash determinism holds within a
  single Python process; tests run in one process per ``pytest`` invocation,
  so golden tests are reproducible.
- ``EmbeddingProviderUnavailable`` is an ``ImportError`` subclass so callers
  can isolate "extra not installed" from genuine bugs in the embedding path.
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from typing import Any

import numpy as np

EMBEDDING_DIMS: int = 384


class EmbeddingProviderUnavailable(ImportError):
    """Raised when an embedding backend cannot be loaded (e.g. ``[vectors]`` extra missing).

    REQ-19: subclass of ``ImportError`` so callers can catch both this and a
    raw missing-module error with a single ``except ImportError`` clause.
    The default message includes the install hint per spec REQ-19.
    """

    def __init__(self, message: str | None = None) -> None:
        if message is None:
            message = (
                "Embedding provider unavailable. "
                "Install [vectors] extra: pip install flow-engineering[vectors]"
            )
        super().__init__(message)


class EmbeddingProvider(ABC):
    """Abstract base for text embedding models (REQ-19).

    The contract:
    - ``embed(texts)`` returns an ``np.ndarray`` of shape ``(len(texts), dim)``.
    - ``dim`` and ``model_version`` describe the output shape and provenance.
    - ``embed_batch`` is the high-throughput path (defaults to ``embed`` per text;
      concrete classes may override to batch into a single model call).

    The default ``embed_batch`` walks ``embed()`` — fine for tests, slow for
    production. Production impls (``SentenceTransformersProvider`` in PR#2)
    override with a single ``model.encode(texts)`` call.
    """

    EMBEDDING_DIMS: int = EMBEDDING_DIMS

    model_version: str
    dim: int

    @abstractmethod
    def embed(self, texts: list[str]) -> np.ndarray:
        """Embed ``texts`` into a ``(len(texts), dim)`` float32 array."""

    def embed_batch(self, texts: list[str]) -> np.ndarray:
        """Default batched impl: walk ``embed()`` per text. Override for speed."""
        return self.embed(texts)


class MockEmbeddingProvider(EmbeddingProvider):
    """Deterministic hash-based vectors for tests (REQ-19 scenarios 1, 4).

    Each row is generated by mapping ``hash(text + str(i)) % 1000 / 1000.0``
    for ``i in range(EMBEDDING_DIMS)``, then L2-normalizing to unit length.
    Same input → same vector within a Python process; different inputs →
    different vectors; L2 norm ≈ 1.0 (±1% tolerance).
    """

    model_version: str = "mock-v1"
    dim: int = EMBEDDING_DIMS

    def __init__(self) -> None:
        self.model_version = "mock-v1"
        self.dim = EMBEDDING_DIMS

    def embed(self, texts: list[str]) -> np.ndarray:
        if not texts:
            return np.zeros((0, EMBEDDING_DIMS), dtype=np.float32)
        rows: list[list[float]] = []
        for t in texts:
            row = [
                (hash(t + str(i)) % 1000) / 1000.0
                for i in range(EMBEDDING_DIMS)
            ]
            rows.append(row)
        arr = np.asarray(rows, dtype=np.float32)
        # L2-normalize each row to unit length (REQ-19 unit-norm contract).
        norms = np.linalg.norm(arr, axis=1, keepdims=True)
        # Guard against zero-vector rows (would produce NaN on divide).
        zero_mask = norms[:, 0] == 0.0
        if zero_mask.any():
            norms[zero_mask] = 1.0
        return arr / norms


class SentenceTransformersProvider(EmbeddingProvider):
    """Real embedding provider backed by ``sentence-transformers`` (REQ-19 T2.1).

    Lazy-import strategy:
    - Module-level ``import flow_engineering.embedding_provider`` does NOT pull
      torch or sentence_transformers (verified by
      ``tests/unit/test_embedding_provider.py::test_subprocess_module_import_does_not_pull_torch``).
    - ``__init__`` does a function-body ``import torch`` + ``from sentence_transformers
      import SentenceTransformer`` to check the extra is installed. If either import
      fails, raises :class:`EmbeddingProviderUnavailable` with the install hint.
    - The actual ``SentenceTransformer(...)`` instantiation is lazy: it happens on
      the first ``embed()`` call via :meth:`_ensure_model` and the result is cached
      on ``self._model`` for subsequent calls. This keeps construction cheap (no
      model download, no GPU init) and defers the expensive model load until the
      provider is actually used.

    Output contract (REQ-19 scenarios 1, 4):
    - ``embed(texts)`` returns ``np.ndarray`` of shape ``(len(texts), 384)``,
      ``dtype=float32``.
    - ``embed([])`` returns shape ``(0, 384)`` without touching the model.
    """

    DEFAULT_MODEL: str = "sentence-transformers/all-MiniLM-L6-v2"
    """The default model. 384-dim MiniLM-L6 is the v1 production choice per design D4 + D9."""

    _INSTALL_HINT: str = "pip install flow-engineering[vectors]"

    def __init__(self, model_name: str = DEFAULT_MODEL) -> None:
        # Function-body import — keeps module-level ``import embedding_provider``
        # torch-free (REQ-19 scenario 2). The two imports are checked atomically:
        # torch without sentence_transformers (or vice versa) is treated as
        # "extra not installed" because the runtime needs both.
        try:
            import torch  # noqa: F401  - presence-check only
            from sentence_transformers import SentenceTransformer  # noqa: F401
        except ImportError as exc:
            raise EmbeddingProviderUnavailable(
                f"Install [vectors] extra: {self._INSTALL_HINT}"
            ) from exc
        self.model_name: str = model_name
        self.model_version: str = model_name
        self.dim: int = EMBEDDING_DIMS
        # Lazy: the model is only constructed on the first embed() call so
        # construction itself stays fast and never downloads weights.
        self._model: Any | None = None

    def _ensure_model(self) -> Any:
        """Construct ``SentenceTransformer`` on first call; cache thereafter."""
        if self._model is None:
            from sentence_transformers import SentenceTransformer

            self._model = SentenceTransformer(self.model_name)
        return self._model

    def embed(self, texts: list[str]) -> np.ndarray:
        if not texts:
            # Empty input short-circuits before touching the model — keeps the
            # embed([]) → (0, 384) contract intact even when torch is unavailable
            # at runtime.
            return np.zeros((0, EMBEDDING_DIMS), dtype=np.float32)
        model = self._ensure_model()
        vectors = model.encode(texts, convert_to_numpy=True)
        arr = np.asarray(vectors, dtype=np.float32).reshape(len(texts), EMBEDDING_DIMS)
        return arr


__all__ = [
    "EMBEDDING_DIMS",
    "EmbeddingProvider",
    "EmbeddingProviderUnavailable",
    "MockEmbeddingProvider",
    "SentenceTransformersProvider",
]